<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>new_plain_text</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\"[^\"]*?\")</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?='[^\n]*'.*$)(?!'s\s+[^\n]*'s\s+)('[^\n]*')</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Z]+\_[A-Z]+[A-Z\_]*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)(?:https?|s?ftp|ftps|file|smb|afp|nfs|(x-)?man|gopher|txmt)://\w+\.\w+(?:\.[a-zA-Z_/\?\=\d\-%]+)*</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^((?!\/\/|##).*(?:：|: ))[^\n]*?$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[[^\n]+?\])</string>
			<key>name</key>
			<string>meta.bullet-point.strong.text</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*&gt;&gt;+[^\n]*</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^[\s]*|\b[\s]+)-[^-\s]+?(?=[\s:\|@]+)</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.txt</string>
	<key>uuid</key>
	<string>516bc7ff-03be-4474-a398-b83e20204594</string>
</dict>
</plist>
